language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_npm_run_test_server.pid --make-pidfile --background --exec npm run test-server" # start a Web server
  - sleep 1 # give Web server some time to bind to sockets, etc
